"""
Review State Definition - LangGraph State Management
"""

from typing import TypedDict, List, Dict, Optional, Annotated
import operator


class SecurityFinding(TypedDict):
    """Individual security finding"""
    file: str
    line: Optional[int]
    severity: str  # HIGH, MEDIUM, LOW
    issue_type: str
    description: str
    recommendation: str
    confidence: str  # HIGH, MEDIUM, LOW


class PerformanceFinding(TypedDict):
    """Individual performance finding"""
    file: str
    line: Optional[int]
    issue_type: str
    description: str
    complexity_score: Optional[float]
    recommendation: str


class StyleFinding(TypedDict):
    """Individual style finding"""
    file: str
    line: Optional[int]
    issue_type: str
    description: str
    recommendation: str


class ReviewState(TypedDict):
    """
    State for the code review workflow.
    
    This state is passed through all nodes in the LangGraph workflow.
    Each agent reads from and writes to this shared state.
    """
    
    # Input Configuration
    input_path: str
    output_dir: str
    
    # Ingestion Results
    file_tree: Dict
    total_files: int
    working_directory: str
    source_type: str  # 'git' or 'local'
    is_temp_directory: bool
    
    # Agent Findings (accumulated across parallel execution)
    security_findings: Annotated[List[SecurityFinding], operator.add]
    performance_findings: Annotated[List[PerformanceFinding], operator.add]
    style_findings: Annotated[List[StyleFinding], operator.add]
    
    # Processing Status
    files_processed: Annotated[List[str], operator.add]
    files_skipped: Annotated[List[str], operator.add]
    
    # Final Report
    final_report: str
    report_path: str
    
    # Error Handling
    error: Optional[str]
    warnings: Annotated[List[str], operator.add]


# Default/initial state factory
def create_initial_state(
    input_path: str,
    output_dir: str = "./code_reviews"
) -> ReviewState:
    """
    Create an initial state for the review workflow.
    
    Args:
        input_path: Path or URL to review
        output_dir: Output directory for reports
        
    Returns:
        Initial ReviewState
    """
    return ReviewState(
        # Input
        input_path=input_path,
        output_dir=output_dir,
        
        # Ingestion (to be filled by ingestor)
        file_tree={},
        total_files=0,
        working_directory='',
        source_type='',
        is_temp_directory=False,
        
        # Findings (accumulated by agents)
        security_findings=[],
        performance_findings=[],
        style_findings=[],
        
        # Processing
        files_processed=[],
        files_skipped=[],
        
        # Report (generated by aggregator)
        final_report='',
        report_path='',
        
        # Errors
        error=None,
        warnings=[],
    )
